# Generated by Django 5.2.1 on 2025-06-12 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_image_restaurant_owner_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('restaurant', 'author')},
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
